#!/bin/bash

working_dir=$(pwd)
exportpath=${working_dir}"/../1_export"
article=article.txt


function get_help {
bold=`tput bold`
    normal=`tput sgr0`

    echo -e "${bold}NAME${normal}"
    echo -e "\tindd-exportcheck\n"

    echo -e "${bold}SYNOPSIS${normal}"
    echo -e "\tindd-exportcheck --check | --help\n"

    echo -e "${bold}DESCRIPTION${normal}"
    echo -e "\tDas Skript müsst Ihr aus dem Ordner '1_export' heraus ausrufen. Es schaut
    \t'ob beim Export alle 'article.txt' erzeugt wurden\n"

    echo -e "\tDamit das Skript seine Arbeit aufnimmt, müsst Ihr es
    \tmit dem Parameter "-c" oder "--check" starten\n"

    echo -e "${bold}OPTIONS${normal}"
    echo -e "\t-h / --help"
    echo -e "\t\tDiese Hilfe anzeigen.\n"
    echo -e "\t-c / --check"
    echo -e "\t\tPruefen, ob die 'article.txt' exportiert wurden\n"

    echo -e "${bold}AUTHOR${normal}"
    echo -e "\tWritten by Kristian Kißling, 2015 - 2016\n"

    echo -e "${bold}REPORTING BUGS${normal}"
    echo -e "\tBug Reports to kkissling@linux-magazin.de\n"

    echo -e "${bold}COPYRIGHT${normal}"
    echo -e "\tLicense: GNU Public License v2."
    echo -e "\tThis is free software: you are free  to  change  and  redistribute  it.
    \tThere is NO WARRANTY, to the extent permitted by law."
}

## CONVERT ARTICLE.TXT TO UTF-8 OTHERWISE SCRIPT BREAKS ##
function convert_to_utf8 {

if [ -e article.txt ]; then

    # Workaround, might be removed, if 'wait' and 'sync' work
    cp ${article} article.txt.copy &&
    mv article.txt.copy ${article} &&
    ${iconv} -f ISO-8859-15 -t UTF-8 ${article} -o article.txt.tmp
    wait
    mv article.txt.tmp article.txt
    wait
else
	echo -e "Die Datei 'article.txt' scheint nicht zu existieren."
	exit 0
fi
}


## CONVERT ARTICLE.TXT BACK TO ISO-8859-15 ##
function convert_to_iso8859_15 {

if [ -e article.txt ]; then
    chmod 755 ${article} &&
    wait
    ${iconv} -f UTF-8 -t ISO-8859-15 ${article} -o article.txt.tmp
    wait
    mv article.txt.tmp article.txt
    wait
else
    echo -e "Die Datei 'article.txt' scheint nicht zu existieren."
	exit 0
fi
}


# check, if articles end with <I>author<I> or <I>IT:Infos<I>, else, ask user for action
function mod_check_length {

check_footnote_start=$(grep '^\@IT: *Infos' ${article})
articleend=$(tail -2 ${article} | grep '<I>.*<I>')

    if ! [ "${check_footnote_start}" ] && ! [ "${articleend}" ]; then
        read -p "Womöglich fehlt dem Artikel das Ende. Autor und letzte fünf Zeilen anzeigen? [j/n]" showend
        case ${showend} in
            j | y)
                autor=$(grep '@A:' ${article})
                echo "Autor:"${autor:3}
                tail -n1 ${article}
                ;;
            *)
                exit 0;
                ;;
        esac
    fi
}


function check {
    if [ -d ${exportpath} ]; then
        # List folders with leading digits
        for folder in $(ls -d [[:digit:]]*); do
            if [ -d ${working_dir}/${folder} ]; then
				# and dive into it
                cd ${working_dir}/${folder}
                mod_check_length
				occurence=$(grep '^@#: *ID: *[0-9]' ${article} 2>&1 &)

				if [[ -f ${article} ]]; then
					if [[ -n "${occurence}" ]]; then
						continue
					else
						rot=$(tput setaf 1)
						reset=$(tput sgr0)
						echo -e "Die ID fehlt im Artikel:" ${rot}${folder}${reset}
						missingtoo=true
					fi
				else
					rot=$(tput setaf 1)
					reset=$(tput sgr0)
					echo -e "Datei 'article.txt' fehlt im Ordner:" ${rot}${folder}${reset}
					missing=true
                		fi
            fi
        done

        if [ ${missing} ]; then
				rot=$(tput setaf 1)
				reset=$(tput sgr0)
				echo -e ${rot}"Bitte fehlende 'article.txt' neu exportieren!"${reset}
			else
				green=$(tput setaf 2)
				reset=$(tput sgr0)
				echo -e ${green}"Alle 'article.txt'-Dateien scheinen da zu sein. Juhu!"${reset}
        fi

	if [ ${missingtoo} ]; then
				rot=$(tput setaf 1)
				reset=$(tput sgr0)
				echo -e ${rot}"Bitte fehlende IDs aus dem Zope nachtragen!"${reset}
			else
				green=$(tput setaf 2)
				reset=$(tput sgr0)
				echo -e ${green}"Alle IDs scheinen vorhanden zu sein. Juhu!"${reset}
        fi
    else
		echo -e "Bitte rufe das Skript aus dem Ordner ".../1_export" heraus auf!"
		exit 0
    fi
}


function start {

    if [ "${1}" == "" ] || [ "${1}" == "-h" ] || [ "${1}" == "--help" ]; then
		clear
        get_help
    elif [ "${1}" == "-c" ] || [ "${1}" == "--check" ]; then
		clear
        #convert_to_utf8
        check
        #convert_to_iso8859_15
        mod_check_length
    fi
}

start "${1}"
