#!/bin/bash

working_dir=$(pwd)
exportpath=${working_dir}"/../1_export"
article=article.txt


function get_help {
bold=`tput bold`
    normal=`tput sgr0`

    echo -e "${bold}NAME${normal}"
    echo -e "\tindd-exportcheck\n"

    echo -e "${bold}SYNOPSIS${normal}"
    echo -e "\tindd-exportcheck --check | --help\n"

    echo -e "${bold}DESCRIPTION${normal}"
    echo -e "\tDas Skript müsst Ihr aus dem Ordner '1_export' heraus ausrufen. Es schaut
    \t'ob beim Export alle 'article.txt' erzeugt wurden\n"

    echo -e "\tDamit das Skript seine Arbeit aufnimmt, müsst Ihr es
    \tmit dem Parameter "-c" oder "--check" starten\n"

    echo -e "${bold}OPTIONS${normal}"
    echo -e "\t-h / --help"
    echo -e "\t\tDiese Hilfe anzeigen.\n"
    echo -e "\t-c / --check"
    echo -e "\t\tPruefen, ob die 'article.txt' exportiert wurden\n"

    echo -e "${bold}AUTHOR${normal}"
    echo -e "\tWritten by Kristian Kißling, 2015 - 2016\n"

    echo -e "${bold}REPORTING BUGS${normal}"
    echo -e "\tBug Reports to kkissling@linux-magazin.de\n"

    echo -e "${bold}COPYRIGHT${normal}"
    echo -e "\tLicense: GNU Public License v2."
    echo -e "\tThis is free software: you are free  to  change  and  redistribute  it.
    \tThere is NO WARRANTY, to the extent permitted by law."
}

function check {
    if [ -d ${exportpath} ]; then
        # List folders with leading digits
        for folder in $(ls -d [[:digit:]]*); do
            if [ -d ${working_dir}/${folder} ]; then
				# and dive into it
                cd ${working_dir}/${folder}

				if [ -f ${article} ]; then
					continue
				else
					echo -e "Datei 'article.txt' fehlt im Ordner:" ${folder}
					missing=true
                fi
            fi
        done
        if [ ${missing} ]; then
				rot=$(tput setaf 1)
				reset=$(tput sgr0)
				echo -e ${rot}"Bitte fehlende 'article.txt' neu exportieren!"${reset}
			else
				green=$(tput setaf 2)
				reset=$(tput sgr0)
				echo -e ${green}"Alle 'article.txt'-Dateien scheinen da zu sein. Juhu!"${reset}
        fi
    else
		echo -e "Bitte rufe das Skript aus dem Ordner ".../1_export" heraus auf!"
		exit 0
    fi
}

function start {

    if [ "${1}" == "" ] || [ "${1}" == "-h" ] || [ "${1}" == "--help" ]; then
		clear
        get_help
    elif [ "${1}" == "-c" ] || [ "${1}" == "--check" ]; then
		clear
        check
    fi
}

start "${1}"
