#!/bin/bash

# This script converts all your "article.txt" files to html-format.
# for this, you have to put all your articles in one subfolder and start this script from there
# Then it converts all listings
# TODO Sanity Checks

working_dir=$(pwd)
bin_dir="/opt/lnm/bin"
exportpath=${working_dir}"/../../1_export"
target_folder=${working_dir}"/../../2_checked"
editor=/usr/bin/gedit

## SHOW HELP SECTION
if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    . ${bin_dir}/lm_post_production_modules/mod_get_header.sh

## DRYRUN
elif [ "$1" == "-d" ] || [ "$1" == "--dryrun" ]; then
    # check, if location is your own subfolder in "1_export", for example "kki"
    echo -e "Starting a dry run now. Converts, but then deletes listings, collects errors in 'error.log'"
    if [ -d ${exportpath} ]; then

        # make error.log for sf if non-existing
        if [ -f ${working_dir}/error.log ]; then
            touch ${working_dir}/error.log
            chmod a+x ${working_dir}/error.log
        fi

        ## Insert modules
        # List folders with leading digits and dive into it
        for folder in $(ls -d [[:digit:]]*); do
            if [ -d ${working_dir}/${folder} ]; then
                cd ${working_dir}/${folder}
                echo -e "\nNext article:"${folder}
                echo -e "================================"
                # check converted 'txt'-articles in firefox
                . ${bin_dir}/lm_post_production_modules/mod_html_check.sh

                # this module removes dvd boxes that make no sense online
                . ${bin_dir}/lm_post_production_modules/mod_remove_dvd_box.sh

                # repair errors for xml export
                #. ${bin_dir}/lm_post_production_modules/mod_check_xml_sanity.sh

                # possible dry run of listing generation here
                #. ../modules/mod_extract_listings.sh
                #cd ..
                #rm -fR listings 2>&1
                #cd ..
                while true
                    do
                    read -p "Do you want to change something on the article and/or take a look at the 'error.log' now? [y/n]" error
                        case ${error} in
                        y)
                            ${editor} article.txt &&
                            echo -e "\n"
                            cat ${working_dir}/error.log | more
                            rm ${working_dir}/error.log
                            read -p "Move on to the next article? [y/n]" moveon
                                case ${moveon} in
                                y)
                                    break
                                    ;;
                                *)
                                    exit 0
                                    ;;
                                esac
                            break
                            ;;
                        *)
                            echo -e "Test run finished, move to the next article!"
                            rm ${working_dir}/error.log
                            break
                            ;;
                        esac
                    done
                # go back in your subfolder, for example "kki"
                cd ..
            fi
        done
        echo -e "\nIf all articles look fine, you should now call 'lm_post_production -c' to convert them, extract listings and so on.\n"
    else
        exit 0
    fi

## CONVERT LISTINGS AND MOVE FOLDERS
elif [ "$1" == "-c" ] || [ "$1" == "--convert" ]; then
    # check, if location is your own subfolder in "1_export", for example "kki"
    if [ -d ${exportpath} ]; then

        # make error.log for sf if non-existing
        if [ -f ${working_dir}/error.log ]; then
            touch ${working_dir}/error.log
            chmod a+x ${working_dir}/error.log
        fi

        ## Insert modules
        #
        # list folders and ls into it one by one
        echo -e "Script generates listings now if it finds some..."
        for folder in $(ls -d [[:digit:]]*); do
            if [ -d ${working_dir}/${folder} ]; then
                cd ${working_dir}/${folder}

                # after everything is fine with article.txt, start extracting the listings
                . ${bin_dir}/lm_post_production_modules/mod_extract_listings.sh

                # repair errors for xml export
                . ${bin_dir}/lm_post_production_modules/mod_check_xml_sanity.sh

                # go back in your subfolder, for example "kki"
                cd ..

                # check if $target_folder exists and move just finalized $folder there
                . ${bin_dir}/lm_post_production_modules/mod_move_finalized_folder.sh
            fi
        done
    else
        echo "You need to create a subfolder in '1_export' and start this script from there."
        exit 0
    fi
fi
